# Site settings
title: Gina Codes
email: drawGinadraw@gmail.com
description: "The personal blog for Gina Maini, Functional Programmer in Oakland, CA. All rights reserved."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.gina.codes" # the base hostname & protocol for your site
twitter_username: wiredsis
github_username:  wiredsister
excerpt_separator: ""
highlighter: rouge

# Build settings
markdown: kramdown
sass: 
  style: compressed
paginate: 5
paginate_path: "/blog/page:num/"
gems: [jekyll-paginate]
