# Site settings
title: Gina Codes
email: drawGinadraw@gmail.com
description: "The personal blog for Gina Maini, Front End Developer in New York City. All rights reserved."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "gina.codes" # the base hostname & protocol for your site
twitter_username: thewiredsister
github_username:  wiredsister

# Build settings
markdown: kramdown
sass: 
  style: compressed
paginate: 5
paginate_path: "/blog/page:num/"